name: Build Release Packages

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  RELEASE_FILE_X64_UBUNTU: ffmpeg-x64-ubuntu-${{ github.ref_name }}.tar.gz

jobs:
  build_ubuntu:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install dependency packages
        run: sudo apt install -y yasm

      - name: configure ffmpeg
        run: chmod +x ./config.sh && ./config.sh

      - name: build ffmpeg
        run: make

      - name: Archive
        run: tar -czvf ${{env.RELEASE_FILE_X64_UBUNTU}} ffmpeg

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/${{env.RELEASE_FILE_X64_UBUNTU}}
