name: Build Release Packages

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  RELEASE_FILE_X64_UBUNTU: ffmpeg-x64-ubuntu-${{ github.ref_name }}
  RELEASE_FILE_X64_UBUNTU_ARCHIVE: ${RELEASE_FILE_X64_UBUNTU}.tar.gz

jobs:
  build_ubuntu:
    name: Build and Publish
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install dependency packages
        run: sudo apt install -y yasm

      - name: configure ffmpeg
        run: chmod +x ./config.sh && ./config.sh

      - name: build ffmpeg
        run: make & make install

      - name: Archive
        run: mv deps ${RELEASE_FILE_X64_UBUNTU} && tar -czvf ${{env.RELEASE_FILE_X64_UBUNTU_ARCHIVE}} ${RELEASE_FILE_X64_UBUNTU}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/${{env.RELEASE_FILE_X64_UBUNTU_ARCHIVE}}
